import { QuickCommand } from './types'

export const defaultCommands: QuickCommand[] = [
    {
        id: 'build-start',
        name: '构建并启动',
        description: '安装依赖、构建、测试并启动开发服务',
        category: '开发',
        command: 'npm install\nnpm run build\nnpm run test\nnpm run dev',
        autoEnter: true,
        lineDelay: 600,
        lineDelays: [],
        linePauses: [],
        shortcut: '',
        favorite: true,
        pinned: true,
        usageCount: 0,
        lastUsedAt: null,
        automationRules: [],
    },
    {
        id: 'git-status',
        name: '查看 Git 状态',
        description: '查看当前仓库状态和最近提交',
        category: 'Git',
        command: 'git status\ngit log --oneline -5',
        autoEnter: true,
        lineDelay: 300,
        lineDelays: [],
        linePauses: [],
        shortcut: '',
        favorite: false,
        pinned: false,
        usageCount: 0,
        lastUsedAt: null,
        automationRules: [],
    },
    {
        id: 'diagnose-node',
        name: 'Node 环境诊断',
        description: '查看 Node、npm 和当前路径',
        category: '诊断',
        command: 'node --version\nnpm --version\npwd',
        autoEnter: true,
        lineDelay: 300,
        lineDelays: [],
        linePauses: [],
        shortcut: '',
        favorite: false,
        pinned: false,
        usageCount: 0,
        lastUsedAt: null,
        automationRules: [],
    },
]

export const defaultQuickCommandsConfig = {
    commands: defaultCommands.map(command => {
        const { usageCount: _usageCount, lastUsedAt: _lastUsedAt, ...stored } = command
        return stored
    }),
    customCategories: [],
    categoryOrder: [],
    selectedCommandId: 'build-start',
    selectedCategory: '全部',
    executionMode: 'paste',
    targetMode: 'current',
    failureStrategy: 'manual',
    drawerWidth: 560,
    showToolbarButton: true,
    requireConfirmBeforeExecute: false,
    confirmBroadcast: true,
    exportFileName: 'tabby-windy-quick-commands-{date}.json',
    basicInfoCollapsed: true,
    moreSettingsCollapsed: true,
    previewCollapsed: false,
    recentOutputLimit: 8000,
    logLimit: 200,
}
